name = "qiankui-sub-cf"
main = "packages/worker/src/index.ts"
compatibility_date = "2025-03-01"
workers_dev = true

[assets]
directory = "./packages/web/dist"
binding = "ASSETS"

[vars]
AGGREGATE_TTL_SECONDS = "3600"
MAX_LOG_ENTRIES = "200"

[[kv_namespaces]]
binding = "APP_KV"
id = "ebe4ea790cdb40f2b8fd6c438700e889"
preview_id = "ebe4ea790cdb40f2b8fd6c438700e889"

[[kv_namespaces]]
binding = "CACHE_KV"
id = "ebe4ea790cdb40f2b8fd6c438700e889"
preview_id = "ebe4ea790cdb40f2b8fd6c438700e889"

[triggers]
crons = ["0 * * * *"]
